[package]
name = "rust_pt_article"
version = "0.1.0"
authors = ["Gillett Hernandez <gillett.hernandez@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
rayon = "1.5.0"
toml = "0.5"
num_cpus = "1.13.0"
serde = { version = "1.0.119", features = ["derive"] }
rand = "0.8"
image = "0.23.12"
packed_simd = { version = "0.3.4", package = "packed_simd_2" }
nalgebra = "0.24.0"
ordered-float = "2.0.1"
exr = "0.9.0"
pbr = "1.0.3"
parking_lot = "0.11.1"
crossbeam = "0.8.0"
tobj = "2.0.3"
minifb = "0.19.1"
math = {path = "crates/math"}

[build-dependencies]
serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1.0.61"

[profile.dev]
opt-level = 3
panic='abort'
debug=true

[profile.test]
opt-level = 0

[profile.release]
opt-level = 3
debug = true
lto = 'fat'
incremental = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
